// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RodFlix.Data;

#nullable disable

namespace RodFlix.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230511075045_FirstOne")]
    partial class FirstOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RodFlix.Models.DmCategories", b =>
                {
                    b.Property<byte>("IdDmCategories")
                        .HasColumnType("tinyint");

                    b.Property<string>("CategorieName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.HasKey("IdDmCategories");

                    b.ToTable("DmCategories");

                    b.HasData(
                        new
                        {
                            IdDmCategories = (byte)1,
                            CategorieName = "Ação"
                        },
                        new
                        {
                            IdDmCategories = (byte)2,
                            CategorieName = "Drama"
                        },
                        new
                        {
                            IdDmCategories = (byte)3,
                            CategorieName = "Terror"
                        },
                        new
                        {
                            IdDmCategories = (byte)4,
                            CategorieName = "Horror"
                        },
                        new
                        {
                            IdDmCategories = (byte)5,
                            CategorieName = "Infantil"
                        },
                        new
                        {
                            IdDmCategories = (byte)6,
                            CategorieName = "Aventura"
                        },
                        new
                        {
                            IdDmCategories = (byte)7,
                            CategorieName = "Carros"
                        },
                        new
                        {
                            IdDmCategories = (byte)8,
                            CategorieName = "Documentario"
                        },
                        new
                        {
                            IdDmCategories = (byte)9,
                            CategorieName = "Anime"
                        },
                        new
                        {
                            IdDmCategories = (byte)10,
                            CategorieName = "80s"
                        },
                        new
                        {
                            IdDmCategories = (byte)11,
                            CategorieName = "Romance"
                        });
                });

            modelBuilder.Entity("RodFlix.Models.Movies", b =>
                {
                    b.Property<int>("IdMovie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovie"));

                    b.Property<byte?>("Categoria1")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Categoria2")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Categoria3")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Categoria4")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Categoria5")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Categoria6")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LengthMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMovie");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
